@startuml First practice

actor user
participant "Server side SG/Libertex"
participant Remitex #pink
entity "Client's bank" #pink
actor sysadmin
participant "Libertex notification endpoint"


note right of "Server side SG/Libertex" #Aqua: I1: GET HOSTED PAYMENT PAGE
"Server side SG/Libertex" -> Remitex ++: Request for hosted payment page

Remitex --> user --: hosted payment page to fill out

user -> Remitex ++: Payment confirmation 
Remitex --> user --: OK: Payment requesites for SWIFT wire transfer

activate user #LightSalmon

alt client made SWIFT wire transfer without interruption
    user -> "Client's bank" ++: Make a SWIFT wire transfer
    note left of user #FFAAAA: May take a while
    "Client's bank" --> user --: Bank Wire Confirmation
    user -> Remitex ++: Upload KYC docs
    Remitex --> user --: OK
    deactivate user
else client dicided to upload KYC docs after while
    user -> sysadmin ++: email KYC docs
    sysadmin --> user --: KYC docs uploaded
end

note left of "Server side SG/Libertex" #Aqua: I2: GET TRANSACTION STATUS
"Server side SG/Libertex" -> Remitex ++: Request for a transaction status
Remitex --> "Server side SG/Libertex" --: Reply code

note left of "Server side SG/Libertex" #Aqua: I3: GET NOTIFICATION
"Server side SG/Libertex" -> "Libertex notification endpoint" ++: Hearing a transaction status
"Libertex notification endpoint" --> "Server side SG/Libertex" --: reply_code

@enduml
