@startuml
autonumber

actor Client
actor Manager
participant Terminal
participant UPP
participant PHUB
participant PSA
participant FxBank
participant FxPay
participant dealing
participant SettlePay
participant Kafka

== Client flow ==

activate Kafka

Client -> Terminal ++: Click withdrawal
Terminal -> PHUB ++: getWithdrawalPageLink
par

PHUB -> FxPay ++: getPaymentMethodsConfiguration
FxPay --> PHUB --: MethodsConfiguration
PHUB -> FxBank ++: getWithdrawalRequisites
FxBank --> PHUB --: WD requesites
PHUB -> PHUB : build getWithdrawalMethodsDetails
end

PHUB -> UPP ++: authorizeWithdrawal
UPP -> FxBank ++: getWithdrawalRequests
FxBank --> UPP --: requests
UPP -> PHUB --: link
PHUB --> Client --: link to withdrawal page

Client -> UPP: load link in iframe
UPP --> Client: WD requests page

Client -> UPP ++: Click new request
UPP --> Client --: WD page

deactivate Client

Client -> UPP ++: Choose SettlePay method\nfill amount, chose requisites, presses press withdraw
UPP -> PHUB ++: requestWithdrawal, method = pay_SettlePay_out,\naccountCode, accountCurrency, amount, requesiteId
PHUB -> FxBank ++: createWithdrawal
FxBank -> FxBank : create withdrawal
FxBank --> Kafka : psa-?--all: send withdrawal event :created
FxBank --> PHUB --: inProcessing | Incomplete
PHUB --> UPP --: inProcessing | Incomplete
UPP --> Client --: In processing withdrawal page

== Process withdrawal request ==

FxBank -> dealing ++: changeBalance with operation PAYMENT_OPERATION
activate FxBank
dealing --> FxBank --:  operationId and operationDate
FxBank -> FxBank : Set balance according to dealing response 
FxBank -> Kafka --: fxbank--all: withdrawal :sent

Kafka -> PHUB ++: withdrawal: sent
PHUB -> Kafka --: payment-hub--all: makeTransfer
Kafka --> PSA ++: makeTransfer
PSA -> SettlePay ++: <b><font color=green>POST: /transaction/pay
SettlePay --> PSA --: <b><font color=green>/transaction/pay response \n
PSA -> PSA : update transfer with status
PSA --> Kafka --: psa-?--all: status
SettlePay --> Client --: Result page

...
== Payouts webhook ==
SettlePay -> PSA ++: <b><font color=green>transaction ID
PSA -> SettlePay : <b><font color=green>GET: Get payment status /transaction/find
SettlePay --> PSA --: <b><font color=green>status
PSA -> PSA : update transfer
PSA --> Kafka :  psa-?--all: transfer event
PSA --> SettlePay : <b><font color=green>HTTP 200

...
== Statements ==
    loop loop by async operation configuration
    PSA -> SettlePay ++: <b><font color=green>GET: Get payment status /transaction/find
    activate PSA
    SettlePay --> PSA --: <b><font color=green>status
    PSA -> PSA: update transfer
    PSA --> Kafka --:  psa-?--all: transfer event
    Kafka --> PHUB : psa-?--all: send transfer type = outcomeTransfer, \nstatus=succeeded/failed
    deactivate PSA
end loop

@enduml