@startuml
autonumber

actor Client
actor Manager
participant Terminal
participant UPP
participant PHUB
participant PSA
participant FxBank
participant FxPay
participant dealing
participant Tokenex
participant SettlePay
participant Kafka

== Client flow ==

activate Kafka

Client -> Terminal ++: Click withdrawal
Terminal -> PHUB ++: getWithdrawalPageLink
deactivate Terminal

par
PHUB -> FxPay ++: getPaymentMethodsConfiguration
FxPay --> PHUB --: MethodsConfiguration
PHUB -> FxBank ++: getWithdrawalRequisites
FxBank --> PHUB --: WD requesites
PHUB -> PHUB : build getWithdrawalMethodsDetails <b><font color=green> requisites including tokenizerDetails
end

PHUB -> UPP ++: authorizeWithdrawal \nsave requisites in the internal client's session
UPP -> FxBank ++: getWithdrawalRequests
FxBank --> UPP --: requests
UPP -> PHUB --: link
PHUB --> Client --: link to withdrawal page

Client -> UPP: load link in iframe
UPP --> Client: WD requests page

Client -> UPP ++: Click new request
UPP --> Client --: WD page

deactivate Client

Client -> UPP ++: Choose SettlePay method\nfill amount, chose the requisite
note right: FE

activate UPP

alt is tokenizerDetails empty?
    
    UPP -> Tokenex ++:  <b><font color=green> tokenex.js
    note right of UPP: BE
    Tokenex --> UPP --:    
    UPP -> UPP : Authrization in iFrame with Tokenex context
    note right of UPP: BE
    UPP --> Client ++: card number
    Client -> UPP --: <b><font color=green> input card number
    note right: FE
    UPP -> UPP : transfer requisite token from FE to BE
    note right of UPP: FE
end

UPP -> PHUB --: requestWithdrawal, method = pay_SettlePay_out,\naccountCode, accountCurrency, amount, requesiteId, <b><font color=green> token
deactivate UPP
activate PHUB

opt A card was not tokenized
    PHUB -> FxBank ++: setCustomerWithdrawalRequisite \n<b><font color=green>  token: update(attach) tokenizerDetails to requisite
    FxBank --> PHUB --: updated
end

PHUB -> FxBank ++: createWithdrawal
deactivate PHUB
FxBank -> FxBank : create withdrawal
FxBank --> Kafka : psa-?--all: send withdrawal event :created
FxBank --> PHUB --: inProcessing | Incomplete
PHUB --> UPP --: inProcessing | Incomplete
UPP --> Client --: In processing withdrawal page


== Process withdrawal request ==

FxBank -> dealing ++: changeBalance with operation PAYMENT_OPERATION
activate FxBank
dealing --> FxBank --:  operationId and operationDate
FxBank -> FxBank : Set balance according to dealing response 
FxBank -> Kafka --: fxbank--all: withdrawal :sent

Kafka -> PHUB ++: withdrawal: sent
PHUB -> Kafka --: payment-hub--all: makeTransfer
Kafka --> PSA ++: makeTransfer
PSA -> Tokenex ++: <b><font color=green>detokenization()
Tokenex -> Tokenex : Card number
Tokenex -> SettlePay ++: <b><font color=green>POST: /transaction/pay
SettlePay --> Tokenex : <b><font color=green>/transaction/pay response
Tokenex --> PSA --: <b><font color=green>/transaction/pay response
PSA -> PSA : update transfer with status
PSA --> Kafka --: psa-?--all: status
SettlePay --> Client --: Result page

...
== Payouts webhook ==
SettlePay -> PSA ++: <b><font color=green>transaction ID
PSA -> SettlePay : <b><font color=green>GET: Get payment status /transaction/find
SettlePay --> PSA --: <b><font color=green>status
PSA -> PSA : update transfer
PSA --> Kafka :  psa-?--all: transfer event
PSA --> SettlePay : <b><font color=green>HTTP 200

...
== Statements ==
    loop loop by async operation configuration
    PSA -> SettlePay ++: <b><font color=green>GET: Get payment status /transaction/find
    activate PSA
    SettlePay --> PSA --: <b><font color=green>status
    PSA -> PSA: update transfer
    PSA --> Kafka --:  psa-?--all: transfer event
    Kafka --> PHUB : psa-?--all: send transfer type = outcomeTransfer, \nstatus=succeeded/failed
    deactivate PSA
end loop

@enduml