@startuml
autonumber

actor Client
actor Manager
participant Terminal
participant UPP
participant PHUB
participant PSA
participant FxBank
participant FxPay
participant dealing
participant Pay4Fun
participant Kafka

== Client flow ==

activate Kafka

Client -> Terminal ++: Click withdrawal
Terminal -> PHUB ++: getWithdrawalPageLink
par

PHUB -> FxPay ++: getPaymentMethodsConfiguration
FxPay --> PHUB --: MethodsConfiguration
PHUB -> FxBank ++: getWithdrawalRequisites
FxBank --> PHUB --: WD requesites
PHUB -> PHUB : build getWithdrawalMethodsDetails
end

PHUB -> UPP ++: authorizeWithdrawal
UPP -> FxBank ++: getWithdrawalRequests
FxBank --> UPP --: requests
UPP -> PHUB --: link
PHUB --> Client --: link to withdrawal page

Client -> UPP: load link in iframe
UPP --> Client: WD requests page

Client -> UPP ++: Click new request
UPP --> Client --: WD page

deactivate Client

Client -> UPP ++: Choose Pay4Fun method\nfill amount, chose requisites, presses press withdraw

UPP -> PHUB ++: Request for a user screening
PHUB -> PSA ++: Request for a user screening
PSA -> Pay4Fun ++: <b><font color=green>POST: /1.0/goout/screening/
Pay4Fun --> PSA --: <b><font color=green>/1.0/goout/process/ response \n(redirect URL)
PSA --> PHUB --: Redirect info
PHUB --> UPP --: Redirect info
UPP --> Client --: redirect to screening URL (pay4fun)
Client -> Pay4Fun ++: load screening page
Pay4Fun --> Client --: screening page
Client -> Pay4Fun ++: complete screening
Pay4Fun --> Client --: result page

UPP -> PHUB ++: requestWithdrawal, method = pay_pay4fun_out,\naccountCode, accountCurrency, amount, requesiteId
PHUB -> FxBank ++: createWithdrawal
FxBank -> FxBank : create withdrawal
FxBank --> Kafka : psa-?--all: send withdrawal event :created
FxBank --> PHUB --: inProcessing | Incomplete
PHUB --> UPP --: inProcessing | Incomplete
UPP --> Client --: In processing withdrawal page

== Process withdrawal request ==

FxBank -> dealing ++: changeBalance with operation PAYMENT_OPERATION
activate FxBank
dealing --> FxBank --:  operationId and operationDate
FxBank -> FxBank : Set balance according to dealing response 
FxBank -> Kafka --: fxbank--all: withdrawal :sent

Kafka -> PHUB ++: withdrawal: sent
PHUB -> Kafka --: payment-hub--all: makeTransfer
Kafka --> PSA ++: makeTransfer
PSA -> Pay4Fun ++: <b><font color=green>POST: /1.0/goout/process/
Pay4Fun --> PSA --: <b><font color=green>/1.0/goout/process/ response \n
PSA --> Kafka --: psa-?--all: send transfer type = outcomeTransfer, \nstatus=succeeded/failed

deactivate PSA

...
== Statements ==
    loop loop by async operation configuration
    PSA -> Pay4Fun ++: <b><font color=green>GET: Get payment status /1.0/goout/transaction/
    activate PSA
    Pay4Fun --> PSA --: <b><font color=green>status
    PSA -> PSA: update transfer
    PSA --> Kafka --:  psa-?--all: transfer event
    Kafka --> PHUB : psa-?--all: send transfer type = outcomeTransfer, \nstatus=succeeded/failed
    deactivate PSA
end loop

...
== Convertation ==
Kafka -> PHUB ++: psa-?--all: read transfer event
PHUB --> Kafka --: payment-hub--all: send transfer event

Kafka -> FxBank ++: payment-hub--all: read transfer event
alt : status == successful
FxBank -> FxBank : Convert crypto -> fiats
end
FxBank -> FxBank: save/update withdrawal entity\nchange account balance
FxBank --> Kafka --: fxbank--all: withdrawal event

deactivate Kafka

@enduml
