@startuml first-use

actor Администратор
actor Ответственнный_за_служение

(Согласование даты и времени служения) as (check_resources)
(Согласование порядка служения и участников) as (add_event)
(Включение служения в календарь) as (publishing)

Ответственнный_за_служение -> Администратор
note right of Ответственнный_за_служение #Aqua : Заявка: \n- дата, время\n- план служения

Администратор --> check_resources
Администратор --> add_event
Администратор --> publishing

@enduml