@startuml

title Crypto currency Mercuryo deposits processing flow 

actor user
participant SG_UPP
participant Payment_hub
participant Kafka
participant FxBank
participant Crypto_adapter
participant Mercuryo
participant BlockChain

user -> SG_UPP ++: 1. Fill the deposit form out
SG_UPP -> Kafka ++: Message to get profile info
Kafka -> FxBank ++: Get profile info, \nincluding personal (wallet) crypto address
Kafka <-- FxBank --: Receiving profile info
Payment_hub <-- Kafka --: Personal (wallet) crypto address: Yes/No
alt Wallet crypto address does NOT exist
Payment_hub -> Kafka ++: Creating personal (wallet) crypto \naddress message
note left of Crypto_adapter #Aqua : Crypto adapter INTERFACE1: \nGENERATE ADDRESS
Kafka -> Crypto_adapter ++: btc.generateAddress
Kafka <-- Crypto_adapter --: Personal (wallet) crypto address
Kafka --> SG_UPP --: Get that back

else Wallet crypto address exists
user -> SG_UPP ++: 2. Submitting depostt request
SG_UPP -> Payment_hub ++: Deposit submit
Payment_hub --> Mercuryo ++: Open deposit page
Mercuryo -> Mercuryo ++: Converts fiats to crypto
user -> Mercuryo --: 3. Submit crypto currency order
Mercuryo -> BlockChain ++: Put transaction into the blockchain
Crypto_adapter -> BlockChain ++: 4. Notifications \nfishing
note left of Crypto_adapter #Aqua : Crypto adapter INTERFACE2: \nPROCESS DEPOSIT NOTIFICATIONS
Crypto_adapter <-- BlockChain --: Receiving notifications
Crypto_adapter --> Kafka --: Message with notification
Kafka --> Payment_hub --: Notification received
Payment_hub -> Kafka ++: Transfer crypto to the user's \nWallet crypto address
Kafka -> FxBank --: Update ballance and transactions info

end


@enduml