@startuml MPSA

actor Client
actor Manager
participant Libertex
participant MPSA
participant Bank

Client ->> Libertex  ++: Submit withdraw with MPSA method 

Libertex ->> Libertex ++: Withdrawal request created
deactivate Libertex

Manager ->> Libertex ++: Approve withdrawal request
deactivate Libertex

Libertex ->> Libertex ++: Approved
deactivate Libertex

Libertex ->> MPSA ++: POST: /Credit (bank requisites)
MPSA -->> Libertex --: /Credit request response (XML)

MPSA -> Bank ++: Request bank transfer
Bank --> MPSA --: Transfer completed

MPSA --> Libertex --: Final Transaction Result (XML)

Libertex ->> Libertex --: Withdrawal completed

@enduml

