@startuml

autonumber

title Simplex payouts in STORM using link zero integration positive flow 

legend top left
  Common positive crypto withdrawal sequence diagram except:
  - Antifraud details
  - Create requisites for bank, cup
  - Approve CUP requisites by manager
  - Export of bank payments
end legend

actor user
participant SG_UPP
participant Payment_hub
participant FxPay
participant FxBank
participant PSA
participant Kafka
participant Crypto_adapter
participant Simplex
participant BlockChain

...
== Making the bank wire transfer order ==
...

user -> SG_UPP ++: Chooses the certain bank transfer method, \nand submit the withdrawal request

SG_UPP -> Simplex ++: Redirecting to the \n“Sell-Crypto” widget link
deactivate SimplexA
deactivate SG_UPP

Simplex -> Simplex ++: Make the selling order, \nand get the Simplex'swallet crypto address 
deactivate Simplex
deactivate Simplex

...
== Creating the withdrawal request ==
...

user <-- Simplex ++: Copy-paste the Simplex'swallet crypto address
deactivate Simplex
deactivate Simplex

user -> SG_UPP ++: Chooses the Bitcoin method \n put an amount and Simplex'swallet crypto address \nand submit
deactivate user

SG_UPP -> Payment_hub ++: requestWithdrawal

...
ref over SG_UPP, FxBank: << 2FA process >>\n
...

Payment_hub -> Payment_hub ++: Calculate the solution (PSA) based on \ngetPaymentMethodsConfiguration response
Payment_hub -> FxBank ++: createWithdrawal
FxBank -> FxBank ++: Creating withdrawal request
FxBank --> Payment_hub --: OK
deactivate Payment_hub
deactivate Payment_hub

...
ref over SG_UPP, FxBank: <<Ant-fraud checks>>\n
...

FxBank -> FxBank ++: Request processing (make its staus "SENT")
deactivate FxBank

...
== Processing the withdrawal request ==
...


FxBank -> Kafka ++: withdrawal: sent
activate FxBank
deactivate Kafka

FxBank -> FxPay ++: Simplex_merchant_operation/TRANSFER_MONEY
FxPay -> FxPay ++: Define payment system for output
deactivate FxPay
deactivate FxBank
deactivate FxBank 

FxPay -> Crypto_adapter ++: cryptoCurrency.send
deactivate FxPay
deactivate Kafka
deactivate SimplexA

Crypto_adapter -> BlockChain ++: Put transaction into blockchain
deactivate Crypto_adapter

BlockChain --> Simplex --: OK
note left of Simplex #CCFFFF : Here we are going to \nprocess statments with the provider \nfurther
activate Simplex
deactivate BlockChain
Simplex -> Simplex ++: Process the bank wire transfer
deactivate Simplex
deactivate Crypto_adapter

deactivate Simplex
deactivate BlockChain

...
== Notifications processing ==
...

Crypto_adapter --> Kafka: (as crypto push from crypto_adapter) - Transfer event about successful (failed) withdrawal

activate Kafka
activate Kafka
Kafka --> FxPay: (as crypto push from crypto_adapter) - Transfer event about successful (failed) withdrawal
deactivate Kafka

activate FxPay
FxPay -> FxPay: by provided from crypto_adapter payment_id seek withdrawal transaction
FxPay --> FxBank : update withdrawal status Simplex_fxpay_out\nsuccessed/failed
deactivate FxPay

activate FxBank
FxBank -> FxBank: change status for withdraw \nsuccessed/failed/incomplete
opt if status successed/failed
FxBank -> Kafka : push event withdraw: succeeded/failed status
deactivate FxBank
end

note left of PSA #CCFFFF :  PSA should take a part of the functions \nof FxPay further

@enduml