@startuml
autonumber

actor Client

== Client flow ==
activate Client
Client -> UPP ++: Select LETKNOWPAY method\nfill amount

Client -> UPP : press press deposit
UPP -> PHUB ++: requestDeposit\nmethod = pay_letknowpay
PHUB -> PSA ++: /createIncomeTransfer\npaymentIntegrationCode = pay_letknowpay
PSA -> PSA: save transfer

PSA -> LETKNOWPAY ++: Request the crypto address <b><font color=green>POST: /get_deposit_address

LETKNOWPAY --> PSA --: Crypto address

PSA --> PHUB --: Crypto address
PHUB --> UPP --: Crypto address
UPP -> Client --: Crypto address

== Deposit given Crypto address ==

Note right of PHUB
    EITHER WAY CHOSEN BY CLIENT TO DEPOSIT GIVEN CRYPTO ADDRESS
                                   (OUT OF SCOPE)
end note

== Updating transaction status ==

Client -> UPP ++: load result page
UPP -> PHUB ++: updateIncomeTransfer\nwith transferId
PHUB -> PSA ++: updateIncomeTransfer\nwith transferId
PSA -> PSA: get transfer from DB

group Listening callback
    LETKNOWPAY --> PSA --: <b><font color=green>status
    PSA -> PSA: update transfer
    PSA --> Kafka: transfer event
    PSA --> LETKNOWPAY: <b><font color=green>HTTP 200
end
    PSA -> PSA: update transfer
    PSA --> Kafka: psa-?--all: send transfer event
    deactivate LETKNOWPAY    


PSA -> PHUB --: Ok, transfer status
PHUB -> UPP --: Ok, transfer status
UPP -> Client --: result page
deactivate Client

@enduml