@startuml first-use

actor user

(Buying crypto currency) as (Use_common)
(Get quote) as (Use_quote)
(Submit order) as (Use_order)
(Make payment) as (Use_payment)
(Update account) as (Use_account)

user --> Use_common
Use_common --> Use_quote

note right of Use_order #Aqua : Based on the \nquote information

Use_common --> Use_order
Use_order --> Use_payment

Use_quote --> Use_account
Use_order --> Use_account
Use_payment --> Use_account

@enduml