@startuml libertex-use

title <b>Сonveyor scheme</b>


left to right direction

actor (Managing mechanism)

rectangle "Source1"
rectangle "Source2"
rectangle "Source3"
rectangle "Source4"
rectangle "..."
rectangle "SourceN"

usecase node11
usecase  node21
usecase  node31
usecase  node41
usecase node_1
usecase  nodeN1

usecase node12
usecase node22
usecase node32
usecase node42
usecase node_2
usecase nodeN2
usecase nodeN21

usecase node13
usecase node23
usecase node33
usecase node43
usecase node_3
usecase nodeN3

usecase node14
usecase node24
usecase node34
usecase node44
usecase node_4
usecase nodeN4

usecase nodeFinal

Source1 --> node11
Source2 --> node21
Source3 --> node31
Source4 --> node41
... --> node_1
SourceN --> nodeN1

node11 --> node12
(Additional loads) -up-> node12
node21 --> node22
node31 --> node32
node41 --> node42
node_1 --> node_2
nodeN1 --> nodeN2
nodeN1 --> nodeN21
nodeN2 --> nodeN21

node12 --> node13
node22 --> node23
node32 --> node33
node42 --> node43
node_2 --> node_3
nodeN21 --> nodeN3

node13 --> node14
node23 --> node24
node33 --> node34
node43 --> node44
node_3 --> node_4
nodeN3 --> nodeN4

node14 --> nodeFinal
node24 --> nodeFinal
node34 --> nodeFinal
node44 --> nodeFinal
node_4 --> nodeFinal
nodeN4 --> nodeFinal

@enduml