@startuml libertex-use

title <b>libertex-use</b>

actor cryptoAddress
actor merchantAddress
actor clientAddress

usecase (Buy using client crypto address) as useClient
usecase (Buy using merchant crypto address) as useMerchant

merchantAddress -up-|> cryptoAddress
clientAddress -up-|> cryptoAddress

newpage

merchantAddress -- useMerchant
clientAddress -- useClient

@enduml