@startuml
title <b>Payment integration classification </b>\n 

[FxPay] -up-> [PS integrations] : ???
[Direct method] -up-> [PS integrations]
[Constructor] -up-> [PS integrations]

[Easy Payment Gateway (EPG)] -up-> [Constructor]
[Payment Gateways Adapter (PGA)] -up-> [Constructor] : ???

[getPaymentIntegrations] -up-> [Payment Gateways Adapter (PGA)]

[Payment Hub Core <b>(15 methods)</b>] -up-> [Constructor] : ???
[Payment Hub Adapters <b>(11 methods)</b>] -up-> [Constructor] : ???
[UPP service] -up-> [Easy Payment Gateway (EPG)]
[UPP service] -up-> [FxPay]

@enduml