@startuml
Shape <|-- Circle
Shape : +getSquare()

Circle : -radius

Shape : -name
Shape : -color
Shape : +getColor()

Shape <|-- Rectangle
Rectangle : -length
Rectangle : -width

Shape <|-- Triangle
Triangle : -side_a
Triangle : -side_b
Triangle : -side_c

Shape <|-- Ellipse
Ellipse : -semi_minor_axis
Ellipse : -semi_major_axis

@enduml
