@startuml
autonumber

actor Client
participant PaymentPage
participant Backend
participant PSA
participant Monetix
participant PIX


Client -> PaymentPage: User select Monetix method \nand press press deposit
activate PaymentPage

PaymentPage -> Backend --: Request for deposit
activate Backend

Backend -> PSA: /createIncomeTransfer
activate PSA

PSA -> Monetix: /payment/sale
activate Monetix

Monetix --> PSA --: /payment/sale response
deactivate Monetix

PSA --> Backend: transfer in status "inProgress"
deactivate PSA
deactivate Backend

PSA -> Backend ++: Get redirect URP from Callback

Backend --> Client --: Get a user redirected to \na checkout page

Client -> PIX ++: Confirm payment
PIX -> PIX : Bank transfer
PIX --> PaymentPage --: OK

PaymentPage --> Client --: OK

PSA -> Monetix ++: Get payment status /payment/status
Monetix --> PSA --: /payment/status response

PSA --> Backend : /payment/status response

Monetix -> Backend ++: Send callbacks with a transaction info
Backend -> Backend --: Get status info from callbacks

@enduml