@startuml
autonumber

actor Client
participant PaymentPage
participant Backend
participant PSA
participant Simplex
participant Blockchain


Client -> PaymentPage: User selects payment method, \npresses deposit
activate PaymentPage

PaymentPage -> Backend --: Request for deposit
activate Backend

Backend -> PSA ++: /createIncomeTransfer

PSA -> Simplex ++: /quote
Simplex --> PSA --: rate
deactivate PSA

PSA -> Simplex ++: /partner/data
activate PSA

Simplex -> Simplex : Confirm payment with \nSimplex bank department

Simplex --> PSA --: "is_kyc_update_required"
deactivate Simplex
deactivate PSA

PSA --> Backend: transfer in status "inProgress"
deactivate Backend

PSA -> Simplex ++: POST /payments/new
Simplex --> Client --: Get a user redirected to \na checkout page

Client -> Simplex ++: Confirm payment
Simplex --> PaymentPage --: OK

Simplex -> Blockchain ++: Push crypto payment
Blockchain --> Simplex --: Get notification


loop

PSA -> Simplex: /events
activate Simplex

Simplex --> PSA: [events array]
deactivate Simplex

activate PSA
PSA -> PSA --: check event by payment_id

end

PSA -> Backend: payment successful

PSA -> Simplex: delete events/{id}
activate Simplex

Simplex -> Simplex: delete event by id

Simplex --> PSA: status ok
deactivate Simplex



@enduml