@startuml

title Common Simplex bank wire deposits flow

autonumber

actor user
participant StormGain
participant Simplex
participant Bank
participant BlockChain

user -> StormGain ++: Submit deposit

StormGain -> Simplex ++: Redirect to Simplex
deactivate StormGain

Simplex -> Simplex ++: Adjust currencies, and ammmount, \nput crypto wallet address
deactivate Simplex

Simplex -> Simplex ++: Checking user
deactivate Simplex

Simplex -> Simplex ++: Make payment request
deactivate Simplex

Simplex --> user ++: Show bank requesites to user
deactivate Simplex

user -> user ++: Copy-paste bank requesites to user

user -> Bank ++: Submit payment
deactivate user
deactivate user

Bank -> Bank ++: Process payment
deactivate Bank
Bank --> Simplex ++: Payment confirmation
deactivate Bank

Simplex -> BlockChain ++: Transfer crypto to the user's wallet


@enduml